package generatedbyassl.as.aes.customera.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'SendInterfaceInActiveMsg' (specified as FUNCTION ASSL tier).
 */
public class SENDINTERFACEINACTIVEMSG
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDINTERFACEINACTIVEMSG' class.
	 */
	static private SENDINTERFACEINACTIVEMSG oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDINTERFACEINACTIVEMSG (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDINTERFACEINACTIVEMSG' class.
	 */
	static public SENDINTERFACEINACTIVEMSG getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDINTERFACEINACTIVEMSG();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.customera.aeip.channels.PRIVATE_LINK.getInstance().putMessage("generatedbyassl.as.aes.customera.aeip.messages.INTERFACEINACTIVEMSG", generatedbyassl.as.aes.customera.aeip.messages.INTERFACEINACTIVEMSG.getInstance());
	}

}