package generatedbyassl.as.asip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'sendDeviceCrashedMsg' (specified as FUNCTION ASSL tier).
 */
public class SENDDEVICECRASHEDMSG
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDDEVICECRASHEDMSG' class.
	 */
	static private SENDDEVICECRASHEDMSG oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDDEVICECRASHEDMSG (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDDEVICECRASHEDMSG' class.
	 */
	static public SENDDEVICECRASHEDMSG getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDDEVICECRASHEDMSG();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.asip.channels.PUBLIC_LINK.getInstance().putMessage("generatedbyassl.as.asip.messages.MSGDEVICECRASHED", generatedbyassl.as.asip.messages.MSGDEVICECRASHED.getInstance());
	}

}