package generatedbyassl.as.aes.customera.metrics;

import java.io.Serializable;
import generatedbyassl.as.ASSLMETRIC;
import java.lang.Float;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'BandwidthA' (specified as METRIC ASSL tier).
 */
public class BANDWIDTHA
	extends ASSLMETRIC
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'BANDWIDTHA' class.
	 */
	static private BANDWIDTHA oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * The metric's value - ASSL VALUE {} clause.
	 */
	public Float VALUE = new Float(10);
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the old VALUE of the metric.
	 */
	protected Float oldVALUE = new Float(10);

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  BANDWIDTHA (  )
	{
		METRIC_TYPE = "RESOURCE";
		DESCRIPTION = "This is the bandwidth for customer A!";
		MEASURE_UNIT = "Mbit/s";
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'BANDWIDTHA' class.
	 */
	static public BANDWIDTHA getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new BANDWIDTHA();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Checks whether the metric is valid. A metric is considered valid (true) iff the value it is holding satisfies all the threshold class values.
	 */
	public synchronized boolean isValid (  )
	{
		boolean bValid = false;
		int iEqlLeft = VALUE.compareTo(  new Float( 5 ) );
		int iEqlRght = VALUE.compareTo(  new Float( 10 ) );
		if ( (iEqlLeft >= 0) &&
			 (iEqlRght <= 0) ) 
		{
			bValid = true;
		}
		else
		{
			bValid = false;
		}
		return bValid;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Updates the metric value.
	 */
	public synchronized void refresh (  )
	{
		//**** checks if the metric has changed its VALUE since the last refresh
		int iEql = VALUE.compareTo( oldVALUE );
		if ( iEql == 0 ) 
		{
			bHasChanged = false;
		}
		else
		{
			oldVALUE = new Float( VALUE.floatValue() );
			bHasChanged = true;
		}
	}

}