package generatedbyassl.as.aes.customera.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InUnsatisfiedBandwidthSimulation' (specified as FLUENT ASSL tier).
 */
public class INUNSATISFIEDBANDWIDTHSIMULATION
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INUNSATISFIEDBANDWIDTHSIMULATION' class.
	 */
	static private INUNSATISFIEDBANDWIDTHSIMULATION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INUNSATISFIEDBANDWIDTHSIMULATION (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.customera.events.TIMETOSIMULATEUNSATISFIEDBANDWIDTH.getInstance() );
		generatedbyassl.as.aes.customera.events.TIMETOSIMULATEUNSATISFIEDBANDWIDTH.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.customera.events.UNSATISFIEDBANDWIDTH.getInstance() );
		generatedbyassl.as.aes.customera.events.UNSATISFIEDBANDWIDTH.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.customera.events.CUSTOMERAINUNSATISFIEDBANDWIDTH.getInstance() );
		generatedbyassl.as.aes.customera.events.CUSTOMERAINUNSATISFIEDBANDWIDTH.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INUNSATISFIEDBANDWIDTHSIMULATION' class.
	 */
	static public INUNSATISFIEDBANDWIDTHSIMULATION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INUNSATISFIEDBANDWIDTHSIMULATION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}