package generatedbyassl.as.aes.customera.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;
import java.lang.Boolean;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'CheckBandwidthIssues' (specified as ACTION ASSL tier).
 */
public class CHECKBANDWIDTHISSUES
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CHECKBANDWIDTHISSUES' class.
	 */
	static private CHECKBANDWIDTHISSUES oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a variable/collection specified in the ASSL specification.
	 */
	public Boolean DEVICEACTIVE = Boolean.FALSE;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CHECKBANDWIDTHISSUES (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CHECKBANDWIDTHISSUES' class.
	 */
	static public CHECKBANDWIDTHISSUES getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CHECKBANDWIDTHISSUES();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.customera.aeself_management.self_healing.INUNSATISFIEDBANDWIDTH.getInstance().isFluentInitiated()  &&  generatedbyassl.as.aes.customera.metrics.BANDWIDTHA.getInstance().isValid()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.customera.actions.CHECKBANDWIDTHISSUES.getInstance().DEVICEACTIVE = true ;
		generatedbyassl.as.aes.customera.actions.CHECKINTERFACE.getInstance().perform(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		if (  (  !  generatedbyassl.as.aes.customera.actions.CHECKBANDWIDTHISSUES.getInstance().DEVICEACTIVE  )  ) 
		{
			generatedbyassl.as.aes.customera.events.INTERFACEINACTIVE.getInstance().triggerEvent();
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is not successfully performed.
	 */
	public void ONERR_TRIGGERS (  )
	{
		generatedbyassl.as.aes.customera.events.INTERFACENOTCHECKED.getInstance().triggerEvent();
	}

}