package generatedbyassl.as.aes.customera.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'ServiceSinProgress' (specified as ACTION ASSL tier).
 */
public class SERVICESINPROGRESS
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SERVICESINPROGRESS' class.
	 */
	static private SERVICESINPROGRESS oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SERVICESINPROGRESS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SERVICESINPROGRESS' class.
	 */
	static public SERVICESINPROGRESS getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SERVICESINPROGRESS();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.customera.aeself_management.self_healing.INSERVICES.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.customera.aeip.managed_elements.SERVICES.getInstance().SERVICESINT(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.aes.customera.events.SERVICESTIMOUT.getInstance().triggerEvent();
	}

}