package generatedbyassl.as.aes.customera.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'ServiceS' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class SERVICES
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SERVICES' class.
	 */
	static private SERVICES oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SERVICES (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SERVICES' class.
	 */
	static public SERVICES getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SERVICES();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void SERVICESINT (  )
	{
		//**** Implement this method.
	}

}