package generatedbyassl.as.aes.coordinator.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'CheckDevice' (specified as ACTION ASSL tier).
 */
public class CHECKDEVICE
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CHECKDEVICE' class.
	 */
	static private CHECKDEVICE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CHECKDEVICE (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CHECKDEVICE' class.
	 */
	static public CHECKDEVICE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CHECKDEVICE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.aes.coordinator.events.DEVICECHECKED.getInstance().triggerEvent();
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is not successfully performed.
	 */
	public void ONERR_TRIGGERS (  )
	{
		generatedbyassl.as.autonomicnetwork.events.DEVICECRASHED.getInstance().triggerEvent();
	}

}