package generatedbyassl.as.aes.coordinator.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'Coordinator' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class COORDINATOR
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'COORDINATOR' class.
	 */
	static private COORDINATOR oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  COORDINATOR (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'COORDINATOR' class.
	 */
	static public COORDINATOR getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new COORDINATOR();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void GETBANDWIDTHA (  )
	{
		//**** Implement this method.
	}

}